### ISSUE TITLE
prettier-plugin-tailwindcss

### ISSUE THREAD

**Issue by Guanyuhao** [zanminkian/git-validator#102]
✖ npx git-validator -u:
[error] require() of ES Module /Users/xxx/Desktop/code/practice/getting-started-example/node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.4_prettier@3.0.3/node_modules/prettier-plugin-tailwindcss/dist/index.mjs not supported.
[error] Instead change the require of /Users/xxx/Desktop/code/practice/getting-started-example/node_modules/.pnpm/prettier-plugin-tailwindcss@0.5.4_prettier@3.0.3/node_modules/prettier-plugin-tailwindcss/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.

**Comment by zanminkian** [comment]
看起来是因为你的项目用了tailwind，并且根目录有一个tailwind的配置文件。我也用tailwind，但是我没有出现这个问题。麻烦提供一下可复现的仓库🙏

**Comment by zanminkian** [comment]
我有一个使用tailwind的模板仓库，这个仓库里面运行没有出现你报告的问题。里面配置都很简单，可以参考一下有什么出入：https://github.com/zanminkian/react-boilerplate

**Comment by zanminkian** [comment]
麻烦尝试下v0.10.8，应该修复了你的问题。如果还有问题，可以随时打开这个issue。
