### ISSUE TITLE
请问 支持 package.json 在 .git 的子目录下的结构吗

### ISSUE THREAD

**Issue by weicong** [zanminkian/git-validator#132]
请问 支持 package.json 在 .git 的子目录下的结构里安装吗

```
/project
    .git
    /frontend
        package.json   -- 在此安装？
```

**Comment by zanminkian** [comment]
@weicong 不支持。这种场景第一次见，为什么项目会在`.git`的子目录下？

**Comment by weicong** [comment]
有一些项目，可能只需要一个程序员维护，所以前后端在一个 git 库里，结构大概是这个样子

https://scottsauber.com/2021/06/01/using-husky-git-hooks-and-lint-staged-with-nested-folders/
https://www.interglobalmedianetwork.com/blog/adding-husky-to-a-subfolder-of-a-git-root-repository

**Comment by zanminkian** [comment]
如果是前后端都放在一起的项目（monorepo），合理结构应该是
```
├── .git/
├── frontend/
│   └── package.json -> 不是这里
├── backend/
│   └── package.json
├── package.json -> 安装在这里
├── pnpm-lock.yaml
├── pnpm-workspace.yaml
└── tsconfig.json
```
安装在子项目的package.json的话，意义不是很大，因为同一个仓库的代码风格应该一致。
如果非要这样做，可以在根目录添加一个`lint-staged.config.js`
```js
module.exports = {
  "frontend/**/*": "git-validator -u"
}
```

**Comment by weicong** [comment]
@zanminkian 好，多谢

**Comment by zanminkian** [comment]
先关闭了哈，有任何问题再重新提issue或者再打开当前issue
