### ISSUE TITLE
eslint配置能否被vscode-eslint插件识别？

### ISSUE THREAD

**Issue by gezhicui** [zanminkian/git-validator#154]
eslint的配置在@git-validator/eslint-config中，是不是只有运行lint命令的时候，配置才生效？如果我在vscode编辑器中下载了vscode-eslint插件，在保存文件时自动校验，那插件能识别到@git-validator/eslint-config的配置吗

**Comment by gezhicui** [comment]
好的  谢谢

**Comment by zanminkian** [comment]
另一个办法是开发一个vscode插件专门适配git-validator，类似[xo的vscode插件](https://github.com/xojs/vscode-linter-xo)（xo也是一款all-in-one的代码风格校验器）。但是开发插件的成本较高，目前没时间。
